### ISSUE TITLE
Provide option to disable warnings

### ISSUE THREAD

**Issue by skyrpex** [SamVerschueren/babel-engine-plugin#4]
Would you accept a PR with a configuration option to disable warnings?

Regards,

**Comment by SamVerschueren** [comment]
Can you give an example of a warning? I guess I would accept an option `silent` which is `false` by default.

**Comment by skyrpex** [comment]
I mean [this warning](https://github.com/SamVerschueren/babel-engine-plugin/blob/master/lib/babel-module-template.js#L34). I can make a screenshot but wel... 😆

**Comment by skyrpex** [comment]
How would the option be passed? Now, the constructor arguments are `constructor(compilation, babelOptions)`. There are multiple ways, but maybe the best are the following:

- There could be a third argument for the silent option, among others: `constructor(compilation, babelOptions, { silent })`.
- The arguments could be changed to: `constructor(compilation, { babel, silent })`.

I actually prefer the last one, but it's not backwards compatible. There's another way, but it implies mixing silent within the babel options, which is dangerous.

**Comment by sindresorhus** [comment]
Not sure this is a good idea. People will then just silence the warnings rather than actually fix them. There's a reason it's a warning. This plugin is unable to determine whether the package needs transpilation or not. Ignoring warnings could potentially cause broken builds.

**Comment by skyrpex** [comment]
You have a point there.

**Comment by dimaturishchev** [comment]
Hello,

I think it will still be very helpful if you provide the option to disable warnings (as a last resort). 
I got your point that silencing the warning instead of actually fixing them is not a good idea, but there is a warning about 3rd party packages don't specify the targeted Node.js version in their package.json `engines` field which can't be fixed quickly on the developer's side. A lot of CIs are configured the way that they will fail builds if there are warnings and there is no way to fix the warnings caused by 3rd party libraries quickly.

**Comment by SamVerschueren** [comment]
What CIs fail when warnings are printed on screen? That's just wrong, it's a warning, not an error.
